.TH YKMAN "1" "February 2021" "ykman 4.0.0" "User Commands"
.SH NAME
ykman \- YubiKey Manager (ykman)
.SH SYNOPSIS
.B ykman
[\fI\,OPTIONS\/\fR] \fI\,COMMAND \/\fR[\fI\,ARGS\/\fR]...
.SH DESCRIPTION
.PP
Configure your YubiKey via the command line.
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR SERIAL
Specify which YubiKey to interact with by serial number.
.TP
\fB\-r\fR, \fB\-\-reader\fR NAME
Use an external smart card reader. Conflicts with --device and list.
.TP
\fB\-l\fR, \fB\-\-log\fR-level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
Enable logging at given verbosity level.
.TP
\fB\-\-log\-file\fR FILE
Write logs to the given FILE instead of standard error; ignored unless --log-level
is also set.
.TP
\fB\-\-diagnose\fR
Show diagnostics information useful for troubleshooting.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information about the app
.TP
\fB\-\-full\-help\fR
Show --help, including hidden commands, and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this message and exit.
.SS "Commands:"
.TP
info
Show general information.
.TP
list
List connected YubiKeys.
.TP
config
Enable/Disable applications.
.TP
fido
Manage the FIDO applications.
.TP
oath
Manage the OATH application.
.TP
openpgp
Manage the OpenPGP application.
.TP
otp
Manage the YubiOTP application.
.TP
piv
Manage the PIV application.
.SH EXAMPLES
.PP
List connected YubiKeys, only output serial number:
.PP
$ ykman list --serials
.PP
Show information about YubiKey with serial number 0123456:
.PP
$ ykman --device 0123456 info
