.TH YKMAN "1" "January 2021" "ykman 3.1.2" "User Commands"
.SH NAME
ykman \- YubiKey Manager (ykman)
.SH SYNOPSIS
.B ykman
[\fI\,OPTIONS\/\fR] \fI\,COMMAND \/\fR[\fI\,ARGS\/\fR]...
.SH DESCRIPTION
.PP
Configure your YubiKey via the command line.
.SH OPTIONS
.HP
\fB\-v\fR, \fB\-\-version\fR
.HP
\fB\-d\fR, \fB\-\-device\fR SERIAL
.TP
\fB\-l\fR, \fB\-\-log\-level\fR [DEBUG|INFO|WARNING|ERROR|CRITICAL]
Enable logging at given verbosity level.
.TP
\fB\-\-log\-file\fR FILE
Write logs to the given FILE instead of
standard error; ignored unless \fB\-\-log\-level\fR
is also set.
.TP
\fB\-r\fR, \fB\-\-reader\fR NAME
Use an external smart card reader. Conflicts
with \fB\-\-device\fR and list.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this message and exit.
.SS "Commands:"
.TP
config
Enable/Disable applications.
.TP
fido
Manage FIDO applications.
.TP
info
Show general information.
.TP
list
List connected YubiKeys.
.TP
mode
Manage connection modes (USB Interfaces).
.TP
oath
Manage OATH Application.
.TP
openpgp
Manage OpenPGP Application.
.TP
otp
Manage OTP Application.
.TP
piv
Manage PIV Application.
.SH EXAMPLES
.PP
List connected YubiKeys, only output serial number:
.PP
$ ykman list --serials
.PP
Show information about YubiKey with serial number 0123456:
.PP
$ ykman --device 0123456 info
