.TH YKMAN "1" "January 2024" "ykman 5.3.0" "User Commands"
.SH NAME
ykman \- YubiKey Manager (ykman)
.SH SYNOPSIS
.B ykman
[\fI\,OPTIONS\/\fR] \fI\,COMMAND \/\fR[\fI\,ARGS\/\fR]...
.SH DESCRIPTION
.PP
Configure your YubiKey via the command line.
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR SERIAL
specify which YubiKey to interact with by serial number
.TP
\fB\-r\fR, \fB\-\-reader\fR NAME
specify a YubiKey by smart card reader name (can't be used with \-\-device or list)
.TP
\fB\-l\fR, \fB\-\-log\-level\fR [ERROR|WARNING|INFO|DEBUG|TRAFFIC]
enable logging at given verbosity level
.TP
\fB\-\-log\-file\fR FILE
write log to FILE instead of printing to stderr (requires \-\-log\-level)
.TP
\fB\-\-diagnose\fR
show diagnostics information useful for troubleshooting
.TP
\fB\-v\fR, \fB\-\-version\fR
show version information about the app
.TP
\fB\-\-full\-help\fR
show \-\-help output, including hidden commands
.TP
\fB\-h\fR, \fB\-\-help\fR
show this message and exit
.SS "Commands:"
.TP
info
show general information
.TP
list
list connected YubiKeys
.TP
script
run a python script
.TP
config
enable or disable applications
.TP
fido
manage the FIDO applications
.TP
hsmauth
manage the YubiHSM Auth application
.TP
oath
manage the OATH application
.TP
openpgp
manage the OpenPGP application
.TP
otp
manage the YubiOTP application
.TP
piv
manage the PIV application
.SH EXAMPLES
.PP
List connected YubiKeys, only output serial number:
.PP
$ ykman list --serials
.PP
Show information about YubiKey with serial number 123456:
.PP
$ ykman --device 123456 info
