stub: ykman
releaseType: public
jobs:
  - name: sign-source
    platform: linux
    steps:
      - id: 1
        action: windows
        description: YubiKey Manager
        files:
          - ykman-builds-windows/ykman/ykman.exe
          - ykman-builds-windows/ykman/_internal/pywin32_system32/pythoncom314.dll
          - ykman-builds-windows/ykman/_internal/pywin32_system32/pywintypes314.dll