stub: ykman
releaseType: public
jobs:
  - name: sign-source
    platform: linux
    steps:
      - id: 1
        action: windows
        description: YubiKey Manager
        files:
          - ykman-builds-windows/ykman/ykman.exe