== YubiKey Manager CLI
image:https://travis-ci.org/Yubico/yubikey-manager.svg?branch=master["Build Status", link="https://travis-ci.org/Yubico/yubikey-manager"]

Python library and command line tool for configuring a YubiKey. If you're looking for the full graphical application, which also includes the command line tool, it's https://github.com/Yubico/yubikey-manager-qt[here].

NOTE: This project is in BETA. Any part of the application may change before
the next release, and some functionality and documentation is missing at this
point.

=== Comand line tool
....
Usage: ykman [OPTIONS] COMMAND [ARGS]...

  Configure your YubiKey via the command line.

Options:
  -v, --version
  -h, --help     Show this message and exit.

Commands:
  info     Show general information.
  mode     Manage connection modes.
  openpgp  Manage YubiKey OpenPGP functions.
  slot     Manage YubiKey Slots.
....

=== Installation

==== Ubuntu

    $ sudo apt-add-repository ppa:yubico/stable
    $ sudo apt update
    $ sudo apt install yubikey-manager

==== Pip

    $ pip install yubikey-manager

=== Bash completion

Experimental Bash completion for the command line tool is available, but not 
enabled by default. To enable it, run this command once:

    $ source <(_YKMAN_COMPLETE=source ykman | sudo tee /etc/bash_completion.d/ykman)
