== YubiKey Manager CLI
image:https://travis-ci.org/Yubico/yubikey-manager.svg?branch=master["Build Status", link="https://travis-ci.org/Yubico/yubikey-manager"]
image:https://ci.appveyor.com/api/projects/status/fp7nb97m8372axq8?svg=true["Appveyor Status", link="https://ci.appveyor.com/project/Yubico53275/yubikey-manager"]

Python library and command line tool for configuring a YubiKey. If you're looking for the full graphical application, which also includes the command line tool, it's https://developers.yubico.com/yubikey-manager-qt/[here].

NOTE: This project is in BETA. Any part of the application may change before
the next release, and some functionality and documentation is missing at this
point.

=== Usage
....
Usage: ykman [OPTIONS] COMMAND [ARGS]...

  Configure your YubiKey via the command line.

Options:
  -v, --version
  -h, --help     Show this message and exit.

Commands:
  info     Show general information.
  mode     Manage connection modes.
  oath     Manage YubiKey OATH credentials.
  openpgp  Manage YubiKey OpenPGP functionality.
  piv      Manage YubiKey PIV functionality.
  slot     Manage YubiKey Slots.
....

=== Installation

==== Ubuntu

    $ sudo apt-add-repository ppa:yubico/stable
    $ sudo apt update
    $ sudo apt install yubikey-manager

==== macOS

    $ brew install ykman

Or from source:

    $ brew install swig ykpers libu2f-host libusb
    $ pip install --user yubikey-manager

==== Windows

The command line tool is installed together with the GUI version of https://developers.yubico.com/yubikey-manager-qt/[YubiKey Manager].

==== Pip

    $ pip install yubikey-manager

In order for the pip package to work https://developers.yubico.com/libu2f-host/[libu2f-host], https://developers.yubico.com/yubikey-personalization/[ykpers] and http://libusb.info/[libusb] need to be installed on your system as well.
https://pyscard.sourceforge.io/[Pyscard] is also needed in some form, and if it's not installed pip builds it using http://www.swig.org/[swig] and potentially https://pcsclite.alioth.debian.org/pcsclite.html[PCSC lite].

=== Bash completion

Experimental Bash completion for the command line tool is available, but not 
enabled by default. To enable it, run this command once:

    $ source <(_YKMAN_COMPLETE=source ykman | sudo tee /etc/bash_completion.d/ykman)
