# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Use Ubuntu 16.04 Xenial as a base box.
  config.vm.box = "ubuntu/xenial64"

  # Install dependencies needed for yubikey-manager development.
  config.vm.provision "shell", path: "provision.sh"

  # Uncomment this to add a USB filter for YubiKeys.
  # This will connect the YubiKey to the VM when re-inserted.
  # This filter usess VirtualBox as provider.

  # config.vm.provider "virtualbox" do |vb|
  #  vb.customize ['modifyvm', :id, '--usb', 'on']
  #  vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'YubiKey Filter', '--vendorid', '0x1050', '--productid', '0x0407', '--product', 'Yubikey 4 OTP+U2F+CCID']
  # end 
end
