//! USB HID keyboard scancode tables for YubiKey OTP configuration.
//!
//! Provides scancode mappings for various keyboard layouts, used when
//! programming static passwords or calculating OTP codes.

use std::collections::HashMap;

/// Modifier flag indicating the Shift key is held.
pub const SHIFT: u8 = 0x80;

/// The 16 characters used in modhex encoding.
pub const MODHEX_CHARS: &str = "cbdefghijklnrtuv";

/// Keyboard layout for OTP scancode encoding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeyboardLayout {
    Modhex,
    Us,
    Uk,
    De,
    Fr,
    It,
    Bepo,
    Norman,
}

impl KeyboardLayout {
    /// All available layouts in canonical order.
    pub const ALL: &[KeyboardLayout] = &[
        KeyboardLayout::Modhex,
        KeyboardLayout::Us,
        KeyboardLayout::Uk,
        KeyboardLayout::De,
        KeyboardLayout::Fr,
        KeyboardLayout::It,
        KeyboardLayout::Bepo,
        KeyboardLayout::Norman,
    ];

    /// Layout name as a string.
    pub fn name(self) -> &'static str {
        match self {
            Self::Modhex => "MODHEX",
            Self::Us => "US",
            Self::Uk => "UK",
            Self::De => "DE",
            Self::Fr => "FR",
            Self::It => "IT",
            Self::Bepo => "BEPO",
            Self::Norman => "NORMAN",
        }
    }
}

impl std::str::FromStr for KeyboardLayout {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_uppercase().as_str() {
            "MODHEX" => Ok(Self::Modhex),
            "US" => Ok(Self::Us),
            "UK" => Ok(Self::Uk),
            "DE" => Ok(Self::De),
            "FR" => Ok(Self::Fr),
            "IT" => Ok(Self::It),
            "BEPO" => Ok(Self::Bepo),
            "NORMAN" => Ok(Self::Norman),
            _ => Err(format!("Unknown keyboard layout: {s}")),
        }
    }
}

impl std::fmt::Display for KeyboardLayout {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

/// Returns the USB HID scancode mapping for the given keyboard layout.
pub fn scancodes(layout: KeyboardLayout) -> HashMap<char, u8> {
    match layout {
        KeyboardLayout::Modhex => modhex_scancodes(),
        KeyboardLayout::Us => us_scancodes(),
        KeyboardLayout::Uk => uk_scancodes(),
        KeyboardLayout::De => de_scancodes(),
        KeyboardLayout::Fr => fr_scancodes(),
        KeyboardLayout::It => it_scancodes(),
        KeyboardLayout::Bepo => bepo_scancodes(),
        KeyboardLayout::Norman => norman_scancodes(),
    }
}

fn us_scancodes() -> HashMap<char, u8> {
    let mut m = HashMap::new();
    for (i, c) in "abcdefghijklmnopqrstuvwxyz".chars().enumerate() {
        m.insert(c, 0x04 + i as u8);
        m.insert(c.to_ascii_uppercase(), (0x04 + i as u8) | SHIFT);
    }
    let digits = [
        ('1', 0x1E),
        ('2', 0x1F),
        ('3', 0x20),
        ('4', 0x21),
        ('5', 0x22),
        ('6', 0x23),
        ('7', 0x24),
        ('8', 0x25),
        ('9', 0x26),
        ('0', 0x27),
    ];
    for (c, sc) in digits {
        m.insert(c, sc);
    }
    let symbols = [
        ('\t', 0x2B),
        ('\n', 0x28),
        (' ', 0x2C),
        ('!', 0x1E | SHIFT),
        ('@', 0x1F | SHIFT),
        ('#', 0x20 | SHIFT),
        ('$', 0x21 | SHIFT),
        ('%', 0x22 | SHIFT),
        ('^', 0xA3),
        ('&', 0x24 | SHIFT),
        ('*', 0x25 | SHIFT),
        ('(', 0x26 | SHIFT),
        (')', 0x27 | SHIFT),
        ('-', 0x2D),
        ('_', 0xAD),
        ('=', 0x2E),
        ('+', 0x2E | SHIFT),
        ('[', 0x2F),
        ('{', 0x2F | SHIFT),
        (']', 0x30),
        ('}', 0x30 | SHIFT),
        ('\\', 0x32),
        ('|', 0x32 | SHIFT),
        (';', 0x33),
        (':', 0x33 | SHIFT),
        ('\'', 0x34),
        ('"', 0x34 | SHIFT),
        ('`', 0x35),
        ('~', 0x35 | SHIFT),
        (',', 0x36),
        ('<', 0x36 | SHIFT),
        ('.', 0x37),
        ('>', 0x37 | SHIFT),
        ('/', 0x38),
        ('?', 0x38 | SHIFT),
    ];
    for (c, sc) in symbols {
        m.insert(c, sc);
    }
    m
}

fn modhex_scancodes() -> HashMap<char, u8> {
    let mut m = HashMap::new();
    for c in MODHEX_CHARS.chars() {
        let idx = "abcdefghijklmnopqrstuvwxyz".find(c).unwrap();
        m.insert(c, 0x04 + idx as u8);
        m.insert(c.to_ascii_uppercase(), (0x04 + idx as u8) | SHIFT);
    }
    m
}

fn uk_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('a', 0x04),
        ('b', 0x05),
        ('c', 0x06),
        ('d', 0x07),
        ('e', 0x08),
        ('f', 0x09),
        ('g', 0x0A),
        ('h', 0x0B),
        ('i', 0x0C),
        ('j', 0x0D),
        ('k', 0x0E),
        ('l', 0x0F),
        ('m', 0x10),
        ('n', 0x11),
        ('o', 0x12),
        ('p', 0x13),
        ('q', 0x14),
        ('r', 0x15),
        ('s', 0x16),
        ('t', 0x17),
        ('u', 0x18),
        ('v', 0x19),
        ('w', 0x1A),
        ('x', 0x1B),
        ('y', 0x1C),
        ('z', 0x1D),
        ('A', SHIFT | 0x04),
        ('B', SHIFT | 0x05),
        ('C', SHIFT | 0x06),
        ('D', SHIFT | 0x07),
        ('E', SHIFT | 0x08),
        ('F', SHIFT | 0x09),
        ('G', SHIFT | 0x0A),
        ('H', SHIFT | 0x0B),
        ('I', SHIFT | 0x0C),
        ('J', SHIFT | 0x0D),
        ('K', SHIFT | 0x0E),
        ('L', SHIFT | 0x0F),
        ('M', SHIFT | 0x10),
        ('N', SHIFT | 0x11),
        ('O', SHIFT | 0x12),
        ('P', SHIFT | 0x13),
        ('Q', SHIFT | 0x14),
        ('R', SHIFT | 0x15),
        ('S', SHIFT | 0x16),
        ('T', SHIFT | 0x17),
        ('U', SHIFT | 0x18),
        ('V', SHIFT | 0x19),
        ('W', SHIFT | 0x1A),
        ('X', SHIFT | 0x1B),
        ('Y', SHIFT | 0x1C),
        ('Z', SHIFT | 0x1D),
        ('0', 0x27),
        ('1', 0x1E),
        ('2', 0x1F),
        ('3', 0x20),
        ('4', 0x21),
        ('5', 0x22),
        ('6', 0x23),
        ('7', 0x24),
        ('8', 0x25),
        ('9', 0x26),
        ('\t', 0x2B),
        ('\n', 0x28),
        ('!', SHIFT | 0x1E),
        ('@', SHIFT | 0x34),
        ('\u{a3}', SHIFT | 0x20),
        ('$', SHIFT | 0x21),
        ('%', SHIFT | 0x22),
        ('&', SHIFT | 0x24),
        ('\'', 0x34),
        ('`', 0x35),
        ('(', SHIFT | 0x26),
        (')', SHIFT | 0x27),
        ('*', SHIFT | 0x25),
        ('+', SHIFT | 0x2E),
        (',', 0x36),
        ('-', 0x2D),
        ('.', 0x37),
        ('/', 0x38),
        (':', SHIFT | 0x33),
        (';', 0x33),
        ('<', SHIFT | 0x36),
        ('=', 0x2E),
        ('>', SHIFT | 0x37),
        ('?', SHIFT | 0x38),
        ('"', SHIFT | 0x1F),
        ('[', 0x2F),
        ('#', 0x32),
        (']', 0x30),
        ('^', 0xA3),
        ('_', 0xAD),
        ('{', SHIFT | 0x2F),
        ('}', SHIFT | 0x30),
        ('~', SHIFT | 0x32),
        ('\u{ac}', SHIFT | 0x35),
        (' ', 0x2C),
    ])
}

fn de_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('a', 0x04),
        ('b', 0x05),
        ('c', 0x06),
        ('d', 0x07),
        ('e', 0x08),
        ('f', 0x09),
        ('g', 0x0A),
        ('h', 0x0B),
        ('i', 0x0C),
        ('j', 0x0D),
        ('k', 0x0E),
        ('l', 0x0F),
        ('m', 0x10),
        ('n', 0x11),
        ('o', 0x12),
        ('p', 0x13),
        ('q', 0x14),
        ('r', 0x15),
        ('s', 0x16),
        ('t', 0x17),
        ('u', 0x18),
        ('v', 0x19),
        ('w', 0x1A),
        ('x', 0x1B),
        ('y', 0x1D),
        ('z', 0x1C),
        ('A', SHIFT | 0x04),
        ('B', SHIFT | 0x05),
        ('C', SHIFT | 0x06),
        ('D', SHIFT | 0x07),
        ('E', SHIFT | 0x08),
        ('F', SHIFT | 0x09),
        ('G', SHIFT | 0x0A),
        ('H', SHIFT | 0x0B),
        ('I', SHIFT | 0x0C),
        ('J', SHIFT | 0x0D),
        ('K', SHIFT | 0x0E),
        ('L', SHIFT | 0x0F),
        ('M', SHIFT | 0x10),
        ('N', SHIFT | 0x11),
        ('O', SHIFT | 0x12),
        ('P', SHIFT | 0x13),
        ('Q', SHIFT | 0x14),
        ('R', SHIFT | 0x15),
        ('S', SHIFT | 0x16),
        ('T', SHIFT | 0x17),
        ('U', SHIFT | 0x18),
        ('V', SHIFT | 0x19),
        ('W', SHIFT | 0x1A),
        ('X', SHIFT | 0x1B),
        ('Y', SHIFT | 0x1D),
        ('Z', SHIFT | 0x1C),
        ('0', 0x27),
        ('1', 0x1E),
        ('2', 0x1F),
        ('3', 0x20),
        ('4', 0x21),
        ('5', 0x22),
        ('6', 0x23),
        ('7', 0x24),
        ('8', 0x25),
        ('9', 0x26),
        ('\t', 0x2B),
        ('\n', 0x28),
        ('!', SHIFT | 0x1E),
        ('"', SHIFT | 0x1F),
        ('#', 0x32),
        ('$', SHIFT | 0x21),
        ('%', SHIFT | 0x22),
        ('&', SHIFT | 0x23),
        ('\'', SHIFT | 0x32),
        ('(', SHIFT | 0x25),
        (')', SHIFT | 0x26),
        ('*', SHIFT | 0x30),
        ('+', 0x30),
        (',', 0x36),
        ('-', 0x38),
        ('.', 0x37),
        ('/', SHIFT | 0x24),
        (':', SHIFT | 0x37),
        (';', SHIFT | 0x36),
        ('<', 0x64),
        ('=', SHIFT | 0x27),
        ('>', SHIFT | 0x64),
        ('?', SHIFT | 0x2D),
        ('^', 0x35),
        ('_', SHIFT | 0x38),
        (' ', 0x2C),
        ('`', SHIFT | 0x2D),
        ('\u{a7}', SHIFT | 0x20),
        ('\u{b4}', 0x2E),
        ('\u{c4}', SHIFT | 0x34),
        ('\u{d6}', SHIFT | 0x33),
        ('\u{dc}', SHIFT | 0x2F),
        ('\u{df}', 0x2D),
        ('\u{e4}', 0x34),
        ('\u{f6}', 0x33),
        ('\u{fc}', 0x2F),
    ])
}

fn fr_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('a', 0x14),
        ('b', 0x05),
        ('c', 0x06),
        ('d', 0x07),
        ('e', 0x08),
        ('f', 0x09),
        ('g', 0x0A),
        ('h', 0x0B),
        ('i', 0x0C),
        ('j', 0x0D),
        ('k', 0x0E),
        ('l', 0x0F),
        ('m', 0x33),
        ('n', 0x11),
        ('o', 0x12),
        ('p', 0x13),
        ('q', 0x04),
        ('r', 0x15),
        ('s', 0x16),
        ('t', 0x17),
        ('u', 0x18),
        ('v', 0x19),
        ('w', 0x1D),
        ('x', 0x1B),
        ('y', 0x1C),
        ('z', 0x1A),
        ('A', SHIFT | 0x14),
        ('B', SHIFT | 0x05),
        ('C', SHIFT | 0x06),
        ('D', SHIFT | 0x07),
        ('E', SHIFT | 0x08),
        ('F', SHIFT | 0x09),
        ('G', SHIFT | 0x0A),
        ('H', SHIFT | 0x0B),
        ('I', SHIFT | 0x0C),
        ('J', SHIFT | 0x0D),
        ('K', SHIFT | 0x0E),
        ('L', SHIFT | 0x0F),
        ('M', SHIFT | 0x33),
        ('N', SHIFT | 0x11),
        ('O', SHIFT | 0x12),
        ('P', SHIFT | 0x13),
        ('Q', SHIFT | 0x04),
        ('R', SHIFT | 0x15),
        ('S', SHIFT | 0x16),
        ('T', SHIFT | 0x17),
        ('U', SHIFT | 0x18),
        ('V', SHIFT | 0x19),
        ('W', SHIFT | 0x1D),
        ('X', SHIFT | 0x1B),
        ('Y', SHIFT | 0x1C),
        ('Z', SHIFT | 0x1A),
        ('0', SHIFT | 0x27),
        ('1', SHIFT | 0x1E),
        ('2', SHIFT | 0x1F),
        ('3', SHIFT | 0x20),
        ('4', SHIFT | 0x21),
        ('5', SHIFT | 0x22),
        ('6', SHIFT | 0x23),
        ('7', SHIFT | 0x24),
        ('8', SHIFT | 0x25),
        ('9', SHIFT | 0x26),
        ('\t', 0x2B),
        ('\n', 0x28),
        (' ', 0x2C),
        ('!', 0x38),
        ('"', 0x20),
        ('$', 0x30),
        ('%', SHIFT | 0x34),
        ('&', 0x1E),
        ('\'', 0x21),
        ('(', 0x22),
        (')', 0x2D),
        ('*', 0x31),
        ('+', SHIFT | 0x2E),
        (',', 0x10),
        ('-', 0x23),
        ('.', SHIFT | 0x36),
        ('/', SHIFT | 0x37),
        (':', 0x37),
        (';', 0x36),
        ('<', 0x64),
        ('=', 0x2E),
        ('_', 0x25),
        ('\x7f', 0x2A),
        ('\u{a3}', SHIFT | 0x30),
        ('\u{a7}', SHIFT | 0x38),
        ('\u{b0}', SHIFT | 0x2D),
        ('\u{b2}', 0x35),
        ('\u{b5}', SHIFT | 0x31),
        ('\u{e0}', 0x27),
        ('\u{e7}', 0x26),
        ('\u{e8}', 0x24),
        ('\u{e9}', 0x1F),
        ('\u{f9}', 0x34),
    ])
}

fn it_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('\t', 0x2B),
        ('\n', 0x28),
        (' ', 0x2C),
        ('!', SHIFT | 0x1E),
        ('"', SHIFT | 0x1F),
        ('#', 0x32),
        ('$', SHIFT | 0x21),
        ('%', SHIFT | 0x22),
        ('&', SHIFT | 0x23),
        ('\'', 0x2D),
        ('(', SHIFT | 0x25),
        (')', SHIFT | 0x26),
        ('*', 0x55),
        ('+', 0x30),
        (',', 0x36),
        ('-', 0x38),
        ('.', 0x63),
        ('/', SHIFT | 0x24),
        ('0', 0x27),
        ('1', 0x1E),
        ('2', 0x1F),
        ('3', 0x20),
        ('4', 0x21),
        ('5', 0x22),
        ('6', 0x23),
        ('7', 0x24),
        ('8', 0x25),
        ('9', 0x26),
        (':', 0xB7),
        (';', 0xB6),
        ('<', 0x64),
        ('=', SHIFT | 0x27),
        ('>', SHIFT | 0x64),
        ('?', SHIFT | 0x2D),
        ('@', 0x24),
        ('A', SHIFT | 0x04),
        ('B', SHIFT | 0x05),
        ('C', SHIFT | 0x06),
        ('D', SHIFT | 0x07),
        ('E', SHIFT | 0x08),
        ('F', SHIFT | 0x09),
        ('G', SHIFT | 0x0A),
        ('H', SHIFT | 0x0B),
        ('I', SHIFT | 0x0C),
        ('J', SHIFT | 0x0D),
        ('K', SHIFT | 0x0E),
        ('L', SHIFT | 0x0F),
        ('M', SHIFT | 0x10),
        ('N', SHIFT | 0x11),
        ('O', SHIFT | 0x12),
        ('P', SHIFT | 0x13),
        ('Q', SHIFT | 0x14),
        ('R', SHIFT | 0x15),
        ('S', SHIFT | 0x16),
        ('T', SHIFT | 0x17),
        ('U', SHIFT | 0x18),
        ('V', SHIFT | 0x19),
        ('W', SHIFT | 0x1A),
        ('X', SHIFT | 0x1B),
        ('Y', SHIFT | 0x1C),
        ('Z', SHIFT | 0x1D),
        ('\\', 0x35),
        ('^', 0xAE),
        ('_', 0xB8),
        ('`', SHIFT | 0x2D),
        ('a', 0x04),
        ('b', 0x05),
        ('c', 0x06),
        ('d', 0x07),
        ('e', 0x08),
        ('f', 0x09),
        ('g', 0x0A),
        ('h', 0x0B),
        ('i', 0x0C),
        ('j', 0x0D),
        ('k', 0x0E),
        ('l', 0x0F),
        ('m', 0x10),
        ('n', 0x11),
        ('o', 0x12),
        ('p', 0x13),
        ('q', 0x14),
        ('r', 0x15),
        ('s', 0x16),
        ('t', 0x17),
        ('u', 0x18),
        ('v', 0x19),
        ('w', 0x1A),
        ('x', 0x1B),
        ('y', 0x1C),
        ('z', 0x1D),
        ('|', 0xB5),
        ('\u{a3}', 0xA0),
        ('\u{a7}', 0xB2),
        ('\u{b0}', 0xB4),
        ('\u{e7}', 0xB3),
        ('\u{e8}', 0x2F),
        ('\u{e9}', SHIFT | 0x2F),
        ('\u{e0}', 0x34),
        ('\u{ec}', 0x2E),
        ('\u{f2}', 0x33),
        ('\u{f9}', 0x31),
    ])
}

fn bepo_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('\t', SHIFT | 0x2B),
        ('\n', SHIFT | 0x28),
        (' ', 0x2C),
        ('!', SHIFT | 0x1C),
        ('"', 0x1E),
        ('#', SHIFT | 0x35),
        ('$', 0x35),
        ('%', 0x2E),
        ('\'', 0x11),
        ('(', 0x21),
        (')', 0x22),
        ('*', 0x27),
        ('+', 0x24),
        (',', 0x0A),
        ('-', 0x25),
        ('.', 0x19),
        ('/', 0x26),
        ('0', SHIFT | 0x27),
        ('1', SHIFT | 0x1E),
        ('2', SHIFT | 0x1F),
        ('3', SHIFT | 0x20),
        ('4', SHIFT | 0x21),
        ('5', SHIFT | 0x22),
        ('6', SHIFT | 0x23),
        ('7', SHIFT | 0x24),
        ('8', SHIFT | 0x25),
        ('9', SHIFT | 0x26),
        (':', SHIFT | 0x19),
        (';', SHIFT | 0x0A),
        ('=', 0x2D),
        ('?', SHIFT | 0x11),
        ('@', 0x23),
        ('A', SHIFT | 0x04),
        ('B', SHIFT | 0x14),
        ('C', SHIFT | 0x0B),
        ('D', SHIFT | 0x0C),
        ('E', SHIFT | 0x09),
        ('F', SHIFT | 0x38),
        ('G', SHIFT | 0x36),
        ('H', SHIFT | 0x37),
        ('I', SHIFT | 0x07),
        ('J', SHIFT | 0x13),
        ('K', SHIFT | 0x05),
        ('L', SHIFT | 0x12),
        ('M', SHIFT | 0x34),
        ('N', SHIFT | 0x33),
        ('O', SHIFT | 0x15),
        ('P', SHIFT | 0x08),
        ('Q', SHIFT | 0x10),
        ('R', SHIFT | 0x0F),
        ('S', SHIFT | 0x0E),
        ('T', SHIFT | 0x0D),
        ('U', SHIFT | 0x16),
        ('V', SHIFT | 0x18),
        ('W', SHIFT | 0x30),
        ('X', SHIFT | 0x06),
        ('Y', SHIFT | 0x1B),
        ('Z', SHIFT | 0x2F),
        ('`', SHIFT | 0x2E),
        ('a', 0x04),
        ('b', 0x14),
        ('c', 0x0B),
        ('d', 0x0C),
        ('e', 0x09),
        ('f', 0x38),
        ('g', 0x36),
        ('h', 0x37),
        ('i', 0x07),
        ('j', 0x13),
        ('k', 0x05),
        ('l', 0x12),
        ('m', 0x34),
        ('n', 0x33),
        ('o', 0x15),
        ('p', 0x08),
        ('q', 0x10),
        ('r', 0x0F),
        ('s', 0x0E),
        ('t', 0x0D),
        ('u', 0x16),
        ('v', 0x18),
        ('w', 0x30),
        ('x', 0x06),
        ('y', 0x1B),
        ('z', 0x2F),
        ('\u{a0}', SHIFT | 0x2C),
        ('\u{ab}', 0x1F),
        ('\u{b0}', SHIFT | 0x2D),
        ('\u{bb}', 0x20),
        ('\u{c0}', SHIFT | 0x1D),
        ('\u{c7}', SHIFT | 0x31),
        ('\u{c8}', SHIFT | 0x17),
        ('\u{c9}', SHIFT | 0x1A),
        ('\u{ca}', SHIFT | 0x64),
        ('\u{e0}', 0x1D),
        ('\u{e7}', 0x31),
        ('\u{e8}', 0x17),
        ('\u{e9}', 0x1A),
        ('\u{ea}', 0x64),
    ])
}

fn norman_scancodes() -> HashMap<char, u8> {
    HashMap::from([
        ('a', 0x04),
        ('b', 0x05),
        ('c', 0x06),
        ('d', 0x08),
        ('e', 0x07),
        ('f', 0x15),
        ('g', 0x0A),
        ('h', 0x33),
        ('i', 0x0E),
        ('j', 0x1C),
        ('k', 0x17),
        ('l', 0x12),
        ('m', 0x10),
        ('n', 0x0D),
        ('o', 0x0F),
        ('p', 0x11),
        ('q', 0x14),
        ('r', 0x0C),
        ('s', 0x16),
        ('t', 0x09),
        ('u', 0x18),
        ('v', 0x19),
        ('w', 0x1A),
        ('x', 0x1B),
        ('y', 0x0B),
        ('z', 0x1D),
        ('A', SHIFT | 0x04),
        ('B', SHIFT | 0x05),
        ('C', SHIFT | 0x06),
        ('D', SHIFT | 0x08),
        ('E', SHIFT | 0x07),
        ('F', SHIFT | 0x15),
        ('G', SHIFT | 0x0A),
        ('H', SHIFT | 0x33),
        ('I', SHIFT | 0x0E),
        ('J', SHIFT | 0x1C),
        ('K', SHIFT | 0x17),
        ('L', SHIFT | 0x12),
        ('M', SHIFT | 0x10),
        ('N', SHIFT | 0x0D),
        ('O', SHIFT | 0x0F),
        ('P', SHIFT | 0x11),
        ('Q', SHIFT | 0x14),
        ('R', SHIFT | 0x0C),
        ('S', SHIFT | 0x16),
        ('T', SHIFT | 0x09),
        ('U', SHIFT | 0x18),
        ('V', SHIFT | 0x19),
        ('W', SHIFT | 0x1A),
        ('X', SHIFT | 0x1B),
        ('Y', SHIFT | 0x0B),
        ('Z', SHIFT | 0x1D),
        ('0', 0x27),
        ('1', 0x1E),
        ('2', 0x1F),
        ('3', 0x20),
        ('4', 0x21),
        ('5', 0x22),
        ('6', 0x23),
        ('7', 0x24),
        ('8', 0x25),
        ('9', 0x26),
        ('\t', 0x2B),
        ('\n', 0x28),
        ('!', SHIFT | 0x1E),
        ('"', SHIFT | 0x34),
        ('#', SHIFT | 0x20),
        ('$', SHIFT | 0x21),
        ('%', SHIFT | 0x22),
        ('&', SHIFT | 0x24),
        ('\'', 0x34),
        ('`', 0x35),
        ('(', SHIFT | 0x26),
        (')', SHIFT | 0x27),
        ('*', SHIFT | 0x25),
        ('+', SHIFT | 0x2E),
        (',', 0x36),
        ('-', 0x2D),
        ('.', 0x37),
        ('/', 0x38),
        (':', SHIFT | 0x33),
        (';', 0x13),
        ('<', SHIFT | 0x36),
        ('=', 0x2E),
        ('>', SHIFT | 0x37),
        ('?', SHIFT | 0x38),
        ('@', SHIFT | 0x1F),
        ('[', 0x2F),
        ('\\', 0x32),
        (']', 0x30),
        ('^', 0xA3),
        ('_', 0xAD),
        ('{', SHIFT | 0x2F),
        ('}', SHIFT | 0x30),
        ('|', SHIFT | 0x32),
        ('~', SHIFT | 0x35),
        (' ', 0x2C),
    ])
}
