from typing_extensions import Self

def list_otp_devices() -> list[HidDeviceInfo]: ...
def list_all_hid_devices() -> list[HidDeviceInfo]: ...
def list_fido_devices() -> list[FidoDeviceInfo]: ...

class HidDeviceInfo:
    @property
    def path(self) -> str: ...
    @property
    def pid(self) -> int: ...

class OtpConnection:
    def __init__(self, path: str) -> None: ...
    def get_feature_report(self) -> bytes: ...
    def set_feature_report(self, data: bytes) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

class FidoDeviceInfo:
    @property
    def path(self) -> str: ...
    @property
    def pid(self) -> int: ...

class FidoConnection:
    def __init__(self, path: str, pid: int) -> None: ...
    def call(self, cmd: int, data: bytes) -> bytes: ...
    @property
    def device_version(self) -> tuple[int, int, int]: ...
    @property
    def capabilities(self) -> int: ...
    @property
    def path(self) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
