def format_cred_id(
    issuer: str | None, name: str, oath_type: int, period: int
) -> bytes: ...
def parse_cred_id(cred_id: bytes, oath_type: int) -> tuple[str | None, str, int]: ...
def get_device_id(salt: bytes) -> str: ...
def hmac_sha1(key: bytes, message: bytes) -> bytes: ...
def hmac_verify(key: bytes, message: bytes, expected: bytes) -> bool: ...
def derive_key(salt: bytes, passphrase: str) -> bytes: ...
def hmac_shorten_key(key: bytes, algo: int) -> bytes: ...
def get_challenge(timestamp: int, period: int) -> bytes: ...
def format_code(
    oath_type: int, period: int, timestamp: int, truncated: bytes
) -> tuple[str, int, int]: ...
def build_put_data(
    cred_id: bytes,
    oath_type: int,
    hash_algorithm: int,
    digits: int,
    secret: bytes,
    touch_required: bool,
    counter: int,
) -> bytes: ...
def build_set_key_data(key: bytes, challenge: bytes) -> bytes: ...
def build_validate_data(
    key: bytes, device_challenge: bytes, host_challenge: bytes
) -> bytes: ...
def parse_list_entry(data: bytes) -> tuple[int, bytes]: ...
def parse_b32_key(key: str) -> bytes: ...
