from typing import Self

def list_readers() -> list[str]: ...

class PcscConnection:
    def __init__(self, reader_name: str, exclusive: bool = True) -> None: ...
    def get_atr(self) -> bytes: ...
    def transmit(self, apdu: bytes) -> bytes: ...
    def disconnect(self) -> None: ...
    def connect(self, exclusive: bool = False) -> None: ...
    def reconnect(self, exclusive: bool = True) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
