from typing import Any

def calculate_crc(data: bytes) -> int: ...
def check_crc(data: bytes) -> bool: ...
def modhex_encode(data: bytes) -> str: ...
def modhex_decode(string: str) -> bytes: ...
def tlv_parse(data: bytes, offset: int | None = None) -> tuple[int, int, int, int]: ...
def tlv_encode(tag: int, value: bytes) -> bytes: ...
def int2bytes(value: int, min_len: int = 1) -> bytes: ...
def bytes2int(data: bytes) -> int: ...
def oid_to_string(data: bytes) -> str: ...
def oid_from_string(data: str) -> bytes: ...
def set_override_version(major: int, minor: int, patch: int) -> None: ...

class SmartCardProtocol:
    def __init__(self, connection: Any, ins_send_remaining: int = 0xC0) -> None: ...
    def close(self) -> None: ...
    def configure(
        self, version: tuple[int, ...], force_short: bool | None = None
    ) -> None: ...
    def send_apdu(
        self,
        cla: int,
        ins: int,
        p1: int,
        p2: int,
        data: bytes | None = None,
        le: int = 0,
    ) -> bytes: ...
    def select(self, aid: bytes) -> bytes: ...
    def init_scp(self, key_params: Any) -> None: ...

class OtpProtocol:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    def send_and_receive(
        self,
        slot: int,
        data: bytes | None = None,
        expected_len: int | None = None,
        event: Any | None = None,
        on_keepalive: Any | None = None,
    ) -> bytes | None: ...
    def read_status(self) -> bytes: ...
