from collections.abc import Callable
from typing import Any

def read_info(connection: Any) -> dict[str, Any]: ...
def get_name(
    version: tuple[int, int, int],
    form_factor: int,
    is_sky: bool,
    is_fips: bool,
    pin_complexity: bool,
    serial: int | None,
    usb_supported: int,
    has_nfc: bool,
) -> str: ...
def scan_devices() -> tuple[dict[int, int], int]: ...
def list_devices(transports: list[str]) -> list[NativeYubiKeyDevice]: ...

class NativeYubiKeyDevice:
    @property
    def serial(self) -> int | None: ...
    @property
    def pid(self) -> int | None: ...
    @property
    def transport(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def reader_name(self) -> str | None: ...
    @property
    def hid_path(self) -> str | None: ...
    @property
    def fido_path(self) -> str | None: ...
    @property
    def usb_interfaces(self) -> int: ...
    def info(self) -> dict[str, Any]: ...
    def reinsert(
        self,
        status_cb: Callable[[str], None],
        cancelled_cb: Callable[[], bool],
    ) -> None: ...
