def scp_derive(key: bytes, t: int, context: bytes, l: int = 0x80) -> bytes: ...
def scp_calculate_mac(
    key: bytes, chain: bytes, message: bytes
) -> tuple[bytes, bytes]: ...
def constant_time_eq(a: bytes, b: bytes) -> bool: ...

class ScpState:
    def __init__(
        self,
        key_senc: bytes,
        key_smac: bytes,
        key_srmac: bytes,
        mac_chain: bytes | None = None,
        enc_counter: int | None = 1,
    ) -> None: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def mac(self, data: bytes) -> bytes: ...
    def unmac(self, data: bytes, sw: int) -> bytes: ...
    def decrypt(self, encrypted: bytes) -> bytes: ...
