from typing import Any

def py_list_fido_devices() -> list[dict[str, Any]]: ...

class OathSession:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    @property
    def device_id(self) -> str: ...
    @property
    def has_key(self) -> bool: ...
    @property
    def locked(self) -> bool: ...
    def reset(self) -> None: ...
    def derive_key(self, password: str) -> bytes: ...
    def validate(self, key: bytes) -> None: ...
    def set_key(self, key: bytes) -> None: ...
    def unset_key(self) -> None: ...
    def put_credential(
        self,
        name: str,
        oath_type: int,
        hash_algorithm: int,
        secret: bytes,
        digits: int,
        period: int,
        counter: int,
        issuer: str | None = None,
        touch_required: bool = False,
    ) -> tuple[str, bytes, str | None, str, int, int, bool | None]: ...
    def rename_credential(
        self, credential_id: bytes, name: str, issuer: str | None
    ) -> bytes: ...
    def list_credentials(
        self,
    ) -> list[tuple[str, bytes, str | None, str, int, int, bool | None]]: ...
    def calculate(self, credential_id: bytes, challenge: bytes) -> bytes: ...
    def delete_credential(self, credential_id: bytes) -> None: ...
    def calculate_all(
        self, timestamp: int
    ) -> list[
        tuple[
            str,
            bytes,
            str | None,
            str,
            int,
            int,
            bool | None,
            str | None,
            int | None,
            int | None,
        ]
    ]: ...
    def calculate_code(
        self,
        device_id: str,
        cred_id: bytes,
        issuer: str | None,
        name: str,
        oath_type: int,
        period: int,
        touch_required: bool | None,
        timestamp: int,
    ) -> tuple[str, int, int]: ...

class PivSession:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    @property
    def management_key_type(self) -> int: ...
    def reset(self) -> None: ...
    def get_serial(self) -> int: ...
    def authenticate(self, management_key: bytes) -> None: ...
    def set_management_key(
        self, key_type: int, management_key: bytes, require_touch: bool
    ) -> None: ...
    def verify_pin(self, pin: str) -> None: ...
    def verify_uv(
        self, temporary_pin: bool = False, check_only: bool = False
    ) -> bytes | None: ...
    def verify_temporary_pin(self, pin: bytes) -> None: ...
    def get_pin_attempts(self) -> int: ...
    def change_pin(self, old_pin: str, new_pin: str) -> None: ...
    def change_puk(self, old_puk: str, new_puk: str) -> None: ...
    def unblock_pin(self, puk: str, new_pin: str) -> None: ...
    def set_pin_attempts(self, pin_attempts: int, puk_attempts: int) -> None: ...
    def get_pin_metadata(self) -> tuple[bool, int, int]: ...
    def get_puk_metadata(self) -> tuple[bool, int, int]: ...
    def get_management_key_metadata(self) -> tuple[int, bool, int]: ...
    def get_slot_metadata(self, slot: int) -> tuple[int, int, int, bool, bytes]: ...
    def get_bio_metadata(self) -> tuple[bool, int, bool]: ...
    def sign(self, slot: int, key_type: int, message: bytes) -> bytes: ...
    def decrypt(self, slot: int, cipher_text: bytes) -> bytes: ...
    def calculate_secret(
        self, slot: int, key_type: int, peer_public_key: bytes
    ) -> bytes: ...
    def get_object(self, object_id: int) -> bytes: ...
    def put_object(self, object_id: int, data: bytes | None) -> None: ...
    def get_certificate(self, slot: int) -> bytes: ...
    def put_certificate(self, slot: int, cert_der: bytes, compress: bool) -> None: ...
    def delete_certificate(self, slot: int) -> None: ...
    def put_key(
        self,
        slot: int,
        key_type: int,
        key_der: bytes,
        pin_policy: int,
        touch_policy: int,
    ) -> None: ...
    def generate_key(
        self, slot: int, key_type: int, pin_policy: int, touch_policy: int
    ) -> bytes: ...
    def attest_key(self, slot: int) -> bytes: ...
    def move_key(self, from_slot: int, to_slot: int) -> None: ...
    def delete_key(self, slot: int) -> None: ...
    def check_key_support(
        self,
        key_type: int,
        pin_policy: int,
        touch_policy: int,
        generate: bool,
        fips_restrictions: bool,
    ) -> None: ...

class OpenPgpSession:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    @property
    def aid(self) -> bytes: ...
    def reset(self) -> None: ...
    def get_data(self, data_object: int) -> bytes: ...
    def put_data(self, data_object: int, data: bytes) -> None: ...
    def get_application_related_data(self) -> bytes: ...
    def get_pin_status(self) -> tuple[int, int, int, int, int, int, int]: ...
    def get_signature_counter(self) -> int: ...
    def get_key_information(self) -> dict[int, int]: ...
    def get_generation_times(self) -> dict[int, int]: ...
    def get_fingerprints(self) -> dict[int, bytes]: ...
    def verify_pin(self, pin: str, extended: bool) -> None: ...
    def verify_admin(self, admin_pin: str) -> None: ...
    def unverify_pin(self, pw: int) -> None: ...
    def change_pin(self, pin: str, new_pin: str) -> None: ...
    def change_admin(self, admin_pin: str, new_admin_pin: str) -> None: ...
    def set_reset_code(self, reset_code: str) -> None: ...
    def reset_pin(self, new_pin: str, reset_code: str | None = None) -> None: ...
    def set_signature_pin_policy(self, pin_policy: int) -> None: ...
    def set_pin_attempts(
        self, user_attempts: int, reset_attempts: int, admin_attempts: int
    ) -> None: ...
    def get_kdf(self) -> bytes: ...
    def set_kdf(self, kdf_data: bytes) -> None: ...
    def get_algorithm_attributes(self, key_ref: int) -> bytes: ...
    def get_algorithm_information(self) -> dict[int, list[bytes]]: ...
    def set_algorithm_attributes(self, key_ref: int, attributes: bytes) -> None: ...
    def get_uif(self, key_ref: int) -> int: ...
    def set_uif(self, key_ref: int, uif: int) -> None: ...
    def set_generation_time(self, key_ref: int, timestamp: int) -> None: ...
    def set_fingerprint(self, key_ref: int, fingerprint: bytes) -> None: ...
    def generate_rsa_key(self, key_ref: int, key_size: int) -> bytes: ...
    def generate_ec_key(self, key_ref: int, curve_oid: str) -> bytes: ...
    def get_public_key(self, key_ref: int) -> bytes: ...
    def put_key(self, key_ref: int, key_type: int, components: list[bytes]) -> None: ...
    def delete_key(self, key_ref: int) -> None: ...
    def sign(self, message: bytes, hash_algorithm: int) -> bytes: ...
    def decrypt(self, value: bytes) -> bytes: ...
    def authenticate(self, message: bytes, hash_algorithm: int) -> bytes: ...
    def get_certificate(self, key_ref: int) -> bytes: ...
    def put_certificate(self, key_ref: int, cert_der: bytes) -> None: ...
    def delete_certificate(self, key_ref: int) -> None: ...
    def attest_key(self, key_ref: int) -> bytes: ...
    def get_challenge(self, length: int) -> bytes: ...

class HsmAuthSession:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def reset(self) -> None: ...
    def list_credentials(self) -> list[tuple[str, int, int, bool]]: ...
    def put_credential_symmetric(
        self,
        management_key: bytes,
        label: str,
        key_enc: bytes,
        key_mac: bytes,
        credential_password: bytes,
        touch_required: bool,
    ) -> tuple[str, int, int, bool]: ...
    def put_credential_derived(
        self,
        management_key: bytes,
        label: str,
        derivation_password: str,
        credential_password: bytes,
        touch_required: bool,
    ) -> tuple[str, int, int, bool]: ...
    def put_credential_asymmetric(
        self,
        management_key: bytes,
        label: str,
        private_key: bytes,
        credential_password: bytes,
        touch_required: bool,
    ) -> tuple[str, int, int, bool]: ...
    def generate_credential_asymmetric(
        self,
        management_key: bytes,
        label: str,
        credential_password: bytes,
        touch_required: bool,
    ) -> tuple[str, int, int, bool]: ...
    def get_public_key(self, label: str) -> bytes: ...
    def delete_credential(self, management_key: bytes, label: str) -> None: ...
    def change_credential_password(
        self,
        label: str,
        credential_password: bytes,
        new_credential_password: bytes,
    ) -> None: ...
    def change_credential_password_admin(
        self,
        management_key: bytes,
        label: str,
        new_credential_password: bytes,
    ) -> None: ...
    def put_management_key(
        self, management_key: bytes, new_management_key: bytes
    ) -> None: ...
    def get_management_key_retries(self) -> int: ...
    def calculate_session_keys_symmetric(
        self,
        label: str,
        context: bytes,
        credential_password: bytes,
        card_crypto: bytes | None = None,
    ) -> tuple[bytes, bytes, bytes]: ...
    def calculate_session_keys_asymmetric(
        self,
        label: str,
        context: bytes,
        peer_public_key: bytes,
        credential_password: bytes,
        card_crypto: bytes,
    ) -> tuple[bytes, bytes, bytes]: ...
    def get_challenge(
        self, label: str, credential_password: bytes | None = None
    ) -> bytes: ...

class ManagementSessionCcid:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def read_device_info(self) -> dict[str, Any]: ...
    def write_device_config(
        self,
        enabled_capabilities: dict[str, int],
        reboot: bool,
        cur_lock_code: bytes | None = None,
        new_lock_code: bytes | None = None,
        auto_eject_timeout: int | None = None,
        challenge_response_timeout: int | None = None,
        device_flags: int | None = None,
        nfc_restricted: bool | None = None,
    ) -> None: ...
    def set_mode(
        self, mode_code: int, chalresp_timeout: int, auto_eject_timeout: int
    ) -> None: ...
    def device_reset(self) -> None: ...

class ManagementSessionOtp:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def read_device_info(self) -> dict[str, Any]: ...
    def write_device_config(
        self,
        enabled_capabilities: dict[str, int],
        reboot: bool,
        cur_lock_code: bytes | None = None,
        new_lock_code: bytes | None = None,
        auto_eject_timeout: int | None = None,
        challenge_response_timeout: int | None = None,
        device_flags: int | None = None,
        nfc_restricted: bool | None = None,
    ) -> None: ...
    def set_mode(
        self, mode_code: int, chalresp_timeout: int, auto_eject_timeout: int
    ) -> None: ...

class ManagementSessionFido:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def read_device_info(self) -> dict[str, Any]: ...
    def write_device_config(
        self,
        enabled_capabilities: dict[str, int],
        reboot: bool,
        cur_lock_code: bytes | None = None,
        new_lock_code: bytes | None = None,
        auto_eject_timeout: int | None = None,
        challenge_response_timeout: int | None = None,
        device_flags: int | None = None,
        nfc_restricted: bool | None = None,
    ) -> None: ...
    def set_mode(
        self, mode_code: int, chalresp_timeout: int, auto_eject_timeout: int
    ) -> None: ...

class SecurityDomainSession:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    def authenticate(self, key_params: Any) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def get_data(self, tag: int, data: bytes) -> bytes: ...
    def get_key_information(
        self,
    ) -> dict[tuple[int, int], dict[int, int]]: ...
    def get_card_recognition_data(self) -> bytes: ...
    def get_supported_ca_identifiers(
        self, kloc: bool, klcc: bool
    ) -> dict[tuple[int, int], bytes]: ...
    def get_certificate_bundle(self, kid: int, kvn: int) -> list[bytes]: ...
    def reset(self) -> None: ...
    def store_data(self, data: bytes) -> None: ...
    def store_certificate_bundle(
        self, kid: int, kvn: int, certificates: list[bytes]
    ) -> None: ...
    def store_allowlist(self, kid: int, kvn: int, serials: list[bytes]) -> None: ...
    def store_ca_issuer(self, kid: int, kvn: int, ski: bytes) -> None: ...
    def delete_key(self, kid: int, kvn: int, delete_last: bool) -> None: ...
    def generate_ec_key(
        self, kid: int, kvn: int, curve: int, replace_kvn: int
    ) -> bytes: ...
    def put_key_static(
        self,
        kid: int,
        kvn: int,
        key_enc: bytes,
        key_mac: bytes,
        key_dek: bytes | None,
        replace_kvn: int,
    ) -> None: ...
    def put_key_ec_private(
        self,
        kid: int,
        kvn: int,
        private_key: bytes,
        curve: int,
        replace_kvn: int,
    ) -> None: ...
    def put_key_ec_public(
        self,
        kid: int,
        kvn: int,
        public_key: bytes,
        curve: int,
        replace_kvn: int,
    ) -> None: ...

class YubiOtpSessionCcid:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def get_serial(self) -> int: ...
    def get_config_state(self) -> tuple[tuple[int, int, int], int]: ...
    def put_configuration(
        self,
        slot: int,
        config: bytes,
        acc_code: bytes | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def update_configuration(
        self,
        slot: int,
        config: bytes,
        acc_code: bytes | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def swap_slots(self) -> None: ...
    def delete_slot(self, slot: int, cur_acc_code: bytes | None = None) -> None: ...
    def set_scan_map(
        self, scan_map: bytes, cur_acc_code: bytes | None = None
    ) -> None: ...
    def set_ndef_configuration(
        self,
        slot: int,
        ndef_type: int,
        uri: str | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def calculate_hmac_sha1(self, slot: int, challenge: bytes) -> bytes: ...

class YubiOtpSessionOtp:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    @version.setter
    def version(self, value: tuple[int, ...]) -> None: ...
    def get_serial(self) -> int: ...
    def get_config_state(self) -> tuple[tuple[int, int, int], int]: ...
    def put_configuration(
        self,
        slot: int,
        config: bytes,
        acc_code: bytes | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def update_configuration(
        self,
        slot: int,
        config: bytes,
        acc_code: bytes | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def swap_slots(self) -> None: ...
    def delete_slot(self, slot: int, cur_acc_code: bytes | None = None) -> None: ...
    def set_scan_map(
        self, scan_map: bytes, cur_acc_code: bytes | None = None
    ) -> None: ...
    def set_ndef_configuration(
        self,
        slot: int,
        ndef_type: int,
        uri: str | None = None,
        cur_acc_code: bytes | None = None,
    ) -> None: ...
    def calculate_hmac_sha1(
        self,
        slot: int,
        challenge: bytes,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> bytes: ...

class Ctap2SessionCcid:
    def __init__(self, connection: Any, scp_key_params: Any | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    def selection(
        self,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> None: ...
    def get_info(self) -> dict[str, Any]: ...
    def send_cbor(
        self,
        cmd: int,
        data: bytes | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> bytes: ...
    def reset(
        self,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> None: ...

class Ctap2SessionFido:
    def __init__(self, connection: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def version(self) -> tuple[int, int, int]: ...
    def selection(
        self,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> None: ...
    def get_info(self) -> dict[str, Any]: ...
    def send_cbor(
        self,
        cmd: int,
        data: bytes | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> bytes: ...
    def reset(
        self,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> None: ...

class PinProtocol:
    def __init__(self, version: int) -> None: ...
    @property
    def version(self) -> int: ...

class ClientPinCcid:
    def __init__(
        self,
        session: Ctap2SessionCcid,
        protocol: PinProtocol | None = None,
    ) -> None: ...
    @property
    def protocol(self) -> PinProtocol: ...
    def get_pin_retries(self) -> tuple[int, int | None]: ...
    def get_uv_retries(self) -> int: ...
    def set_pin(self, pin: str) -> None: ...
    def change_pin(self, old_pin: str, new_pin: str) -> None: ...
    def get_pin_token(
        self,
        pin: str,
        permissions: int | None = None,
        permissions_rpid: str | None = None,
    ) -> bytes: ...
    def get_uv_token(
        self,
        permissions: int | None = None,
        permissions_rpid: str | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> bytes: ...
    def close(self, session: Ctap2SessionCcid) -> None: ...

class ClientPinFido:
    def __init__(
        self,
        session: Ctap2SessionFido,
        protocol: PinProtocol | None = None,
    ) -> None: ...
    @property
    def protocol(self) -> PinProtocol: ...
    def get_pin_retries(self) -> tuple[int, int | None]: ...
    def get_uv_retries(self) -> int: ...
    def set_pin(self, pin: str) -> None: ...
    def change_pin(self, old_pin: str, new_pin: str) -> None: ...
    def get_pin_token(
        self,
        pin: str,
        permissions: int | None = None,
        permissions_rpid: str | None = None,
    ) -> bytes: ...
    def get_uv_token(
        self,
        permissions: int | None = None,
        permissions_rpid: str | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> bytes: ...
    def close(self, session: Ctap2SessionFido) -> None: ...

class CredentialManagementCcid:
    def __init__(
        self,
        session: Ctap2SessionCcid,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    @property
    def is_update_supported(self) -> bool: ...
    def get_metadata(self) -> tuple[int, int]: ...
    def enumerate_rps(self) -> list[dict[int, Any]]: ...
    def enumerate_creds(self, rp_id_hash: bytes) -> list[dict[int, Any]]: ...
    def delete_cred(self, credential_id: Any) -> None: ...
    def update_user_info(self, credential_id: Any, user: Any) -> None: ...
    def close(self, session: Ctap2SessionCcid) -> None: ...

class CredentialManagementFido:
    def __init__(
        self,
        session: Ctap2SessionFido,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    @property
    def is_update_supported(self) -> bool: ...
    def get_metadata(self) -> tuple[int, int]: ...
    def enumerate_rps(self) -> list[dict[int, Any]]: ...
    def enumerate_creds(self, rp_id_hash: bytes) -> list[dict[int, Any]]: ...
    def delete_cred(self, credential_id: Any) -> None: ...
    def update_user_info(self, credential_id: Any, user: Any) -> None: ...
    def close(self, session: Ctap2SessionFido) -> None: ...

class ConfigCcid:
    def __init__(
        self,
        session: Ctap2SessionCcid,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def enable_enterprise_attestation(self) -> None: ...
    def toggle_always_uv(self) -> None: ...
    def set_min_pin_length(
        self,
        min_pin_length: int | None = None,
        rp_ids: list[str] | None = None,
        force_change_pin: bool = False,
    ) -> None: ...
    def close(self, session: Ctap2SessionCcid) -> None: ...

class ConfigFido:
    def __init__(
        self,
        session: Ctap2SessionFido,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def enable_enterprise_attestation(self) -> None: ...
    def toggle_always_uv(self) -> None: ...
    def set_min_pin_length(
        self,
        min_pin_length: int | None = None,
        rp_ids: list[str] | None = None,
        force_change_pin: bool = False,
    ) -> None: ...
    def close(self, session: Ctap2SessionFido) -> None: ...

class BioEnrollmentCcid:
    def __init__(
        self,
        session: Ctap2SessionCcid,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def get_fingerprint_sensor_info(self) -> dict[int, Any]: ...
    def enroll_begin(
        self,
        timeout: int | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> dict[int, Any]: ...
    def enroll_capture_next(
        self,
        template_id: bytes,
        timeout: int | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> dict[int, Any]: ...
    def enroll_cancel(self) -> None: ...
    def enumerate_enrollments(self) -> dict[int, Any]: ...
    def set_name(self, template_id: bytes, name: str) -> None: ...
    def remove_enrollment(self, template_id: bytes) -> None: ...
    def close(self, session: Ctap2SessionCcid) -> None: ...

class BioEnrollmentFido:
    def __init__(
        self,
        session: Ctap2SessionFido,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def get_fingerprint_sensor_info(self) -> dict[int, Any]: ...
    def enroll_begin(
        self,
        timeout: int | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> dict[int, Any]: ...
    def enroll_capture_next(
        self,
        template_id: bytes,
        timeout: int | None = None,
        event: object | None = None,
        on_keepalive: object | None = None,
    ) -> dict[int, Any]: ...
    def enroll_cancel(self) -> None: ...
    def enumerate_enrollments(self) -> dict[int, Any]: ...
    def set_name(self, template_id: bytes, name: str) -> None: ...
    def remove_enrollment(self, template_id: bytes) -> None: ...
    def close(self, session: Ctap2SessionFido) -> None: ...

class LargeBlobsCcid:
    def __init__(
        self,
        session: Ctap2SessionCcid,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def read_blob_array(self) -> bytes: ...
    def write_blob_array(self, data: bytes) -> None: ...
    def get_blob(self, large_blob_key: bytes) -> bytes | None: ...
    def put_blob(self, large_blob_key: bytes, data: bytes) -> None: ...
    def delete_blob(self, large_blob_key: bytes) -> None: ...
    def close(self, session: Ctap2SessionCcid) -> None: ...

class LargeBlobsFido:
    def __init__(
        self,
        session: Ctap2SessionFido,
        protocol: PinProtocol,
        pin_token: bytes,
    ) -> None: ...
    def read_blob_array(self) -> bytes: ...
    def write_blob_array(self, data: bytes) -> None: ...
    def get_blob(self, large_blob_key: bytes) -> bytes | None: ...
    def put_blob(self, large_blob_key: bytes, data: bytes) -> None: ...
    def delete_blob(self, large_blob_key: bytes) -> None: ...
    def close(self, session: Ctap2SessionFido) -> None: ...

class WebAuthnClientFido:
    def __init__(
        self,
        connection: Any,
        user_interaction: Any,
        client_data_collector: Any,
    ) -> None: ...
    def make_credential(self, options_json: str) -> str: ...
    def get_assertion(self, options_json: str) -> list[str]: ...
    def close(self) -> None: ...

class WebAuthnClientCcid:
    def __init__(
        self,
        connection: Any,
        user_interaction: Any,
        client_data_collector: Any,
        scp_key_params: Any | None = None,
    ) -> None: ...
    def make_credential(self, options_json: str) -> str: ...
    def get_assertion(self, options_json: str) -> list[str]: ...
    def close(self) -> None: ...
