name: Build ppa packages
# No signing or uploading, just to make sure it doesn't brake

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-add-repository -y ppa:yubico/stable
          sudo apt-get update
          sudo apt-get install -qq git devscripts equivs
          sudo mk-build-deps -i debian/control
          cd ..
          git clone https://github.com/dainnilsson/scripts
      - name: Dry run of make-ppa
        run: ../scripts/make-ppa --force --no-sign --no-upload --dists xenial bionic disco eoan
