name: Windows ARM64

on: [push, pull_request]

permissions: read-all

jobs:
  build-arm64:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python (arm64)
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked

      - name: Run pre-commit hooks
        run: |
          uv tool install pre-commit
          pre-commit run --all-files --verbose

      - name: Run unit tests
        run: uv run pytest -v

      - name: Build (sdist & wheel)
        run: uv build

      - name: Install from tar.gz
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install dist/*.tar.gz
            ykman --version
            [[ -z "$(ykman --version | grep -E 'not found|missing')" ]]
            pip uninstall -y yubikey-manager

      - name: Install from wheel
        shell: bash
        run: |
            pip install dist/*.whl
            ykman --version
            [[ -z "$(ykman --version | grep -E 'not found|missing')" ]]
            pip uninstall -y yubikey-manager

      - name: PyInstaller (ARM64)
        shell: bash
        run: |
          uv run pyinstaller ykman.spec
          dist/ykman/ykman.exe --version
          [[ -z "$(dist/ykman/ykman.exe --version | grep -E 'not found|missing')" ]]

      - name: Copy installer resources
        shell: bash
        run: cp -r resources/win dist/scripts

      - name: Install WiX 5 CLI
        shell: powershell
        run: |
          dotnet tool install --global wix

      - name: Add .NET Global Tools to PATH
        shell: powershell
        run: |
          $toolPath = Join-Path $env:USERPROFILE ".dotnet\tools"
          if (-not ($env:PATH -split ";" | Where-Object { $_ -eq $toolPath })) {
            echo "PATH=$env:PATH;$toolPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Build ARM64 MSI
        working-directory: ./dist
        shell: powershell
        run: .\scripts\make_msi.ps1 -Arch arm64

      - name: Upload ARM64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ykman-builds-windows-arm64
          path: dist